# Generated by Django 3.2.5 on 2021-08-06 21:20

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_categroy_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookName', models.CharField(max_length=100)),
                ('cookNumber', models.CharField(max_length=13)),
                ('kitchenName', models.CharField(max_length=100)),
                ('aboutCook', models.TextField()),
                ('servingSince', models.CharField(max_length=100)),
                ('ordersServedTillDate', models.CharField(max_length=100)),
                ('hasFSSAI', models.BooleanField()),
                ('cookPhoto', models.ImageField(upload_to='images/')),
                ('ingredientQualityUsed', models.CharField(max_length=100)),
                ('cookAddress', models.TextField()),
                ('social', models.JSONField(default=app.models.Cook.jsonfield_default_value)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Order_ID', models.CharField(max_length=100, unique=True)),
                ('Mobile', models.CharField(max_length=13)),
                ('Address', models.TextField()),
                ('Instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField()),
                ('Order_ID', models.CharField(max_length=100, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=13)),
                ('Address', models.TextField()),
                ('cookName', models.CharField(max_length=100)),
                ('dishID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooks', to='app.cook')),
            ],
        ),
        migrations.CreateModel(
            name='Dishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishID', models.CharField(max_length=100, unique=True)),
                ('dishName', models.CharField(max_length=100)),
                ('dishPrice', models.IntegerField()),
                ('dishDescription', models.TextField()),
                ('deliveryTime', models.CharField(max_length=100)),
                ('dishIngredients', models.JSONField(default=app.models.Dishe.jsonfield_default_value)),
                ('servesHowMany', models.IntegerField()),
                ('approxDeliveryCost', models.CharField(max_length=100)),
                ('dishPhotos', models.ImageField(upload_to='images/')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cook')),
            ],
        ),
    ]
