# Generated by Django 3.2.5 on 2021-08-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishe',
            name='pincode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
